services:
  - type: web
    name: telegram-trial-webapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app
    envVars:
      - key: IP2LOCATION_API_KEY
        sync: false
      - key: BLOCKED_COUNTRY_CODE
        value: PK  # Set to "PK" for Pakistan (testing), "IN" for India (production)

  - type: worker
    name: telegram-trial-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TRIAL_CHANNEL_ID
        sync: false
      - key: BASE_URL
        fromService:
          type: web
          name: telegram-trial-webapp
          property: url
      - key: IP2LOCATION_API_KEY
        sync: false
      - key: BLOCKED_COUNTRY_CODE
        value: PK


